// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cO8JxibvUBB6VtLdVb-5iYyoPqLPrHI',
    appId: '1:106580228105:web:d77742c411b398c93220d8',
    messagingSenderId: '106580228105',
    projectId: 'appdev-7d45d',
    authDomain: 'appdev-7d45d.firebaseapp.com',
    storageBucket: 'appdev-7d45d.firebasestorage.app',
    measurementId: 'G-QH95CVBRPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPz-O5Ujy4KT6ZlQH5wAcrWtKBvZQaL0',
    appId: '1:106580228105:android:e423587e03d3639d3220d8',
    messagingSenderId: '106580228105',
    projectId: 'appdev-7d45d',
    storageBucket: 'appdev-7d45d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMJYa1W9SSIoG_ai_9kDo4xeK7x2lrCw',
    appId: '1:106580228105:ios:3d98178e74f4744c3220d8',
    messagingSenderId: '106580228105',
    projectId: 'appdev-7d45d',
    storageBucket: 'appdev-7d45d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYMJYa1W9SSIoG_ai_9kDo4xeK7x2lrCw',
    appId: '1:106580228105:ios:3d98178e74f4744c3220d8',
    messagingSenderId: '106580228105',
    projectId: 'appdev-7d45d',
    storageBucket: 'appdev-7d45d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cO8JxibvUBB6VtLdVb-5iYyoPqLPrHI',
    appId: '1:106580228105:web:ba29edae615ee9363220d8',
    messagingSenderId: '106580228105',
    projectId: 'appdev-7d45d',
    authDomain: 'appdev-7d45d.firebaseapp.com',
    storageBucket: 'appdev-7d45d.firebasestorage.app',
    measurementId: 'G-YT9JHBXVC2',
  );
}
